### ISSUE TITLE
REST API endpoint for Restcomm version

### ISSUE THREAD

**Issue by gvagenas** [RestComm/RestComm-Core#123]
REST API endpoint for Restcomm version

**Comment by brainslog** [comment]
The information that should be made available should be the same as show in server startup, e.g.:

``01:39:07,304 INFO  [org.mobicents.servlet.restcomm.Version] (ServerService Thread Pool -- 54) Release ID: (Mobicents) Mobicents Restcomm 7.3.0.624 (build: Git Hash=r7505975adb940dd0ae9c650ada171d66400db571 date=201505140720)``

It comes from https://github.com/Mobicents/RestComm/blob/master/restcomm/restcomm.commons/src/main/java/org/mobicents/servlet/restcomm/Version.java#L87

**Comment by deruelle** [comment]
Can we close this ? I thought the Version Endpoint was implemented in 7.4.0 ?
