### ISSUE TITLE
Make RVD steps inventory 'floating'

### ISSUE THREAD

**Issue by otsakir** [RestComm/RestComm-Core#232]
quoting from a @ghjansen comment:

Hi! Talking about improvements in editor: I've been thinking if maybe the steps menu located left could follow the page scroll. I missed this feature in my last experience building a app, it becomes non ergonomic as the app's growth.

**Comment by ivelin** [comment]
@ghjansen rocks!

**Comment by ghjansen** [comment]
haha thank you @ivelin - let there be rock!

@otsakir I'm not sure if is the best way to do it, but I used a angular directive called 'ngSticky' that apparently does the work. I found 2 situations testing in Safari and Chrome: 1 - after menu stuck on top, when you drag a step near to workspace area, it goes behind the workspace; 2 - after resize the browser window, the menu seems to loose his width style.

I'm not so good in this tiny adjustments, but I will try some more tests this week. Any hint will be very welcome!

**Comment by otsakir** [comment]
@ghjansen , i looked into your patch. It looks pretty cool and simple. 

I also noticed the first issue you describe. We'll need to do some investigation there. I did some css experimenting without much success. It seems like a stacking/floating issue of the draggable item over other floating elements but further research is required to see what causes it. Maybe some experimenting with a simple empty "workspace" div to see how it behaves and isolate the isue. I don't have much to suggest at the moment...

**Comment by otsakir** [comment]
@ghjansen , i think i have solved issue (1) in an unorthodox way. I lowered the workspace on the right instead of reasing the dragged element. The latter didn't work. The issue seems fixed. I tested on Chrome and Firefox. Can you also take a look?

**Comment by ghjansen** [comment]
Fantastic @otsakir ! I am amazed with the simplicity of your solution, very cool! I tested in Safari, Chrome and Firefox, worked fine. If you agree, we can look for a orthodox way of our implementations in near future, then we'll be able to sleep better.

Thank you for this! Im sorry for not give the proper attention to this issue last week as I said I would, this month begins the final exams season at university.

The issue 2 still there. I will take care of it asap! Thank you again!

**Comment by ivelin** [comment]
Simplicity wins!

**Comment by otsakir** [comment]
That's great @ghjansen , i'm glad it worked. Don't bother finding a better way to do it. Save your strength for more challenging issues. You'll probably have to dig into jquery's draggable logic (because that's what is used at the end), our oun patches on it,  how CSS attributes are managed on dragged elemets... it's all too messy and does not worth it. At some point we'll have to rewrite/redesign the drag & drop implementation we use but it's not a priority right now.

Of course, any solution on (2) is welcome. I'll try figure something out my self too.

**Comment by ghjansen** [comment]
Roger that! I'll send news as I progress.

**Comment by ghjansen** [comment]
ngSticky has its peculiarities @otsakir , so I studied the case in detail and fixed (2) plus another situation that happened after that. Even seems to be working well, these solutions also made me restless, so please let me know if some improvement come to your mind.

**Comment by otsakir** [comment]
I just tested your latest patch @ghjansen . It seems that the steps controls (Say, Play etc.) cannot receive any focus. Can you confirm ?

**Comment by ghjansen** [comment]
Yes @otsakir , my bad, didn't noticed before. The area became focusable by removing "z-index:-1" from workspace. I've tried to replace the negative index at workspace for a positive index at the draggable component (class "ui-draggable-dragging"), but didn't worked as expected yet.

**Comment by ghjansen** [comment]
@otsakir by replacing the static "z-index:-1" for a dynamic controller based on 'dragstart' and 'dragstop' actions (basic-dragdrop.js), it was possible to solve workspace's focus issue and now the negative z-index is used only while dragging elements. Unfortunately, the animation of the element fitting inside the workspace when released is affected by the 'dragstop' event and it runs behind the workspace. It doesn't affects the functionality itself, anyway I can work it out when things get quieter. Please let me know if you notice something more i could do for now.

**Comment by otsakir** [comment]
Firefox works fine as far as i saw. The issue is with chrome. @ghjansen , you can try to disable the animation altogether. We can spare the fancy stuff for now.

**Comment by ghjansen** [comment]
@otsakir i've managed to fix the problem with animation.
The solution was simply wait for the animation to end, and then take action to change the z-index of the workspace. That means, i've migrated the existent logic from 'dragstop' event to 'addStep', and voila. :)

**Comment by otsakir** [comment]
sounds great @ghjansen! just make sure nothing is broken. That was a minor but a hard one ;-)

**Comment by ghjansen** [comment]
@otsakir after merging i've noticed that now with the sticky menu and the nem Email verb, there's no space enough left for audio files list, like shown by the image bellow:

![screen shot 2016-03-03 at 09 08 12](https://cloud.githubusercontent.com/assets/1459428/13499501/766abdec-e13d-11e5-894f-ad9540c0d236.png)

So i've tried the following:
1 - turn the div of audio resources into scrollable: it worked but the space for audio resource seems too small to justify scrolling, and this solution doesn't handle browser resize;
2 - turn the div of the entire inventory into scrollable: it worked nice in terms of scrolling and browser resize, but it messed with the drag&drop verbs behaviour.

So, i'm not sure if the sticky inventory bring more benefits than pain anymore.  😞 wdyt?

**Comment by otsakir** [comment]
@ghjansen , indeed. 

I'm afraid that the angular drag'n'drop customization in in the root of it. It is bad and will cause trouble in the future one way or the other. Apart from the sticky inventory shortcommings, note that we've only supported drag'n'drop for RVD elements into modules. And the reason is that it's not flexible and needs a lot of time fine-tuning its behaviour and fixing styling issues. So, generally it's a *don't touch me 'cause i may brake* case. 

IMO don't spend any more time on it. There will probably be more mature libraries out there and other ways to deal with drag'n'drop in angular already. At some point we can research available libraries and re-write the drag'n'drop implementation as well as improve our UX by further using it.

**Comment by ghjansen** [comment]
@otsakir agreed.
I'll push the merge now and keep the branch until a new plan pops in the horizon.

Thanks! :)

**Comment by otsakir** [comment]
@ghjansen, I'm closing the issue as *won't fix* to keep it out of our radars.
