### ISSUE TITLE
Support 'EndTime' filter in Calls endpoint

### ISSUE THREAD

**Issue by otsakir** [RestComm/RestComm-Core#439]
The Calls endpoint does not support 'EndTime' parameter filtering. 'StartTime' works fine. 'EndTime' filter exists in AdminUI Calls log view but it has no effect.

The Twilio spec does not seem to support it though:
https://www.twilio.com/docs/api/rest/call#list

Shall we add support ?
It seems the feature can be added without breaking the spec. Only extending it.

**Comment by deruelle** [comment]
Yes it does make sense to support it
