### ISSUE TITLE
Use UUID like identifier for RVD projects and directly map to Applications

### ISSUE THREAD

**Issue by otsakir** [RestComm/RestComm-Core#529]
The RVD project naming convention should change. The respective Application SID can be used. It's unique and establishes a hardcoded bond between a project and an Application. 

Implications:
 - an upgrade plan should be made for existing workspaces 
 - existing references to projects that use the project name should also work

**Comment by ghjansen** [comment]
This issue is related to #530 .

**Comment by ghjansen** [comment]
Closed via Pull Request #817.
