### ISSUE TITLE
AdminUI should use Application API when mapping DIDs

### ISSUE THREAD

**Issue by otsakir** [RestComm/RestComm-Core#552]
When a DID is mapped to an application, AdminUI presents a drop down of available RVD applications. This list is currently retrieving apps from RVD.

Since RVD projects are now synced with Application entities, the Application REST api can be used instead to populate this list.

**Comment by ghjansen** [comment]
Something interesting to consider is the possibility to create a filter based on the kind of the application, so only the applications acceptable for that particular occasion will be displayed. For example, the Voice Request URL should display only Voice apps, hiding SMS or USSD apps.

![screen shot 2015-10-20 at 14 19 40](https://cloud.githubusercontent.com/assets/1459428/10613882/00f952d8-7736-11e5-8f3a-c14743cb41cb.png)

**Comment by otsakir** [comment]
At first glance it seemed right.

I'm now wondering whether we should do that filtering on the server or let the server return all the apps and filter on the client. 

Doing it on the server seems appropriate if the number of application starts to grow big and we also support incremental results (return the first 25 and if the user scrolls down retrieve some more) or paging  and searching. For now i vote for getting away with client functionality provided of course that the 'kind' of the application is also returned.

**Comment by ghjansen** [comment]
@gvagenas agreed.

Maybe the request triggered by the dropdown's button could pass a "kind" parameter as filter, then we'll be able to manage the apps list on server side.
To handle the list size on client side, we could turn the dropdown into scrollable and request the next page result when scroll reach the bottom, appending the result to the list. I'm not sure if the following is a good practice, but we could store the loaded list on client side to avoid excessive traffic between client and server for every time one pushes the button.

wdyt @gvagenas ? @otsakir ?

**Comment by ghjansen** [comment]
My bad, noticed now that the dropdown we are currently using is already scrollable.

**Comment by ghjansen** [comment]
Closed via Pull Request #817.
