### ISSUE TITLE
Sync existing RVD projects to Application entities

### ISSUE THREAD

**Issue by otsakir** [RestComm/RestComm-Core#553]
For old workspaces that contain projects that have no respective Application entity some sort of syncing should be done so that the applications are available through the Application API.  

A batch processing when RVD starts that would create Applications out of the projects could work. 

An additional feature would be to store the synchronization state somewhere so that that it's not done again and again. Thoughts?

**Comment by deruelle** [comment]
What does this mean in practice for old workspaces, that users won't be able to see them anymore ?

**Comment by otsakir** [comment]
No, all works as expected regarding AdminUI and RVD. They won't be available using the new Applications rest API though until this issue is resolved.

**Comment by deruelle** [comment]
ok got you, that's fine for now but we should probably have some code that can migrate old existing apps to the new schema

**Comment by ghjansen** [comment]
Closed via Pull Request #817.
