### ISSUE TITLE
No Beep in Conference on Restcomm Cloud

### ISSUE THREAD

**Issue by deruelle** [RestComm/RestComm-Core#627]
When joining RestComm Cloud conference, no beeps can be heard. Similar when participants join a conference, the other participants can't hear a beep when they join.

**Comment by gvagenas** [comment]
Can't reproduce. Tested locally and at cloud.restcomm.com

**Comment by gvagenas** [comment]
For the 3rd participant on a conference room there is no beep

**Comment by gvagenas** [comment]
Tested locally and confirmed working
