### ISSUE TITLE
Some Calls are failing to complete stays with status in_progress

### ISSUE THREAD

**Issue by deruelle** [RestComm/RestComm-Core#632]
Example of call staying in wrong status from the Supervision API 
"sid": "XXX",
      "State": "IN_PROGRESS",
      "direction": "inbound",
      "date_created": "Mon, 9 Nov 2015 16:02:19 +0000",
      "from": "desi",
      "to": "+15126001502",
      "Initial Invite": "sip:+15126001502@cloud.restcomm.com"

and snapshot of the Logs/CDR
![screenshot from 2015-11-10 12 55 18](https://cloud.githubusercontent.com/assets/54279/11062014/98013bde-87ab-11e5-8b3e-05087a4bf6cb.png)

**Comment by gvagenas** [comment]
Patch from #505 cover this issue. Waiting for live test calls and will close this issue

**Comment by deruelle** [comment]
The issue is still present on RestComm cloud.

**Comment by leftyb** [comment]
Tested on Staging server with the latest docker restcomm/restcomm:latest, and is working properly.
