### ISSUE TITLE
Updating account info and saving also updates the current user on the top right

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/RestComm-Core#678]
Scenario:
- login to staging.restcomm.com as admin
- create a new account
- update the new account's 'Friendly Name' and save

At this point the current user as shown on the top right corner will change from Admin to new account name. Shouldn't that remain the name of the currently logged in user?

**Comment by otsakir** [comment]
@atsakiridis , does this mean that you are creating a new sub-account from your sub-account ? This means that we have a three level account hierarchy.

@ghjansen , @deruelle comments  on that ?

If i got this right, according to Gui's schematic, Twilio has two levels and from older discussions we were thinking of doing the same. Shall we modify our policy or fix our "bug" ?

**Comment by deruelle** [comment]
@otsakir I think the use case here is independent of the number of levels. 
From my understanding, this would happen even with administrator@company.com creating a sub account, right @atsakiridis  ?

**Comment by otsakir** [comment]
@deruelle , indeed. I placed the conversation about account levels in the wrong place.

@atsakiridis issue stands of course.
