### ISSUE TITLE
Email REST API documentation

### ISSUE THREAD

**Issue by gvagenas** [RestComm/RestComm-Core#779]

**Comment by deruelle** [comment]
@leftyb can you finalize the Email API documentation at http://docs.telestax.com/restcomm-pages/ ?

**Comment by leftyb** [comment]
@deruelle , sure I will create the document for the Email Rest API.

**Comment by leftyb** [comment]
Documentation added. 
http://docs.telestax.com/restcomm-api-email-messages/
