### ISSUE TITLE
Pass Call SID as an X-Header at the 200 OK Response

### ISSUE THREAD

**Issue by gvagenas** [RestComm/RestComm-Core#814]
If Call SID passes as custom header at the 200 OK Responses, sip clients can make use of the Call SID for LCM.

Olympus, for example can control the call.

**Comment by deruelle** [comment]
If a user is actually dialing a conference. Is it possible to actually get the conference id as well, so the app can query the # of participants and their name/DIDs, etc... ?

**Comment by gvagenas** [comment]
@deruelle The Conference REST API is for that reason. This API is not implemented yet though

**Comment by deruelle** [comment]
https://github.com/RestComm/RestComm-Core/issues/5 right ?

What I meant is pass the Conference ID back as a Header too in the response so the app can use the API from https://github.com/RestComm/RestComm-Core/issues/5 to control things.

**Comment by gvagenas** [comment]
@deruelle Correct issue #5 is the issue for the Conference API.

At the time the Call actor sends the 200 OK the Conference ID is not known, but nevertheless I think this is not needed to control conferences. With the Conference API a user will be able to see running conferences and also participants in the conferences.
Even now that Conference API is not ready , if the CallSID is known. we can control conference participants, such as move them or hangup them etc, using the LiveCallModification.
