### ISSUE TITLE
Move multi-tenancy blog post to docs site

### ISSUE THREAD

**Issue by gvagenas** [RestComm/RestComm-Core#815]
Move http://www.telestax.com/multi-tenancy-support/ to docs.telestax.com/restcomm-pages

**Comment by croufay** [comment]
fixed

This API doc has been updated to reflect the sub-account information 
http://docs.telestax.com/restcomm-api-account/

The Multi-tenancy doc has been moved here
http://docs.telestax.com/restcomm-multi-tenancy-and-managing-sub-accounts/

The original doc has been retired


charles
