### ISSUE TITLE
Deploy RestComm into a telecom network

### ISSUE THREAD

**Issue by yolile** [RestComm/RestComm-Core#823]
Im trying to understand how, after create and deploy my USSD or IVR application into the simulation enviroment of Restcomm, ¿how can I deploy it into a real enviroment, I mean, in a telecom network of my country? I mean, ¿how different are the simulation enviroment and the real enviroment? ¿What is the proccess that I have to follow? 

Thanks

**Comment by deruelle** [comment]
Please open a thread on https://groups.google.com/forum/#!forum/restcomm for such questions as this is not an issue.
