### ISSUE TITLE
LCM workflow fails to clean resources

### ISSUE THREAD

**Issue by hrosa** [RestComm/RestComm-Core#836]
While testing a Live Call Modification scenario, I noticed that RestComm fails to clean MGCP resources properly.

The call scenario was the following:
1. Phone A registers as alice.
2. Phone B calls +1238 (Dial Client). Phone A starts ringing.
3. Perform LCM to dial-conference demo (wait for moderator) with moveConnectedLeg=true. Both clients are placed on hold.
4. Perform LCM to dial-conference-moderator demo, targeting Phone B. Background music stops and both clients can start talking.

According to the [tcpdump](https://github.com/RestComm/RestComm-Core/files/112938/lcm-issue-mgcp.pcapng.zip) trace, the generated media resources and their cleanup process is represented by the following diagram. I am also attaching the [RestComm](https://github.com/RestComm/RestComm-Core/files/112943/lcm-issue-restcomm.txt) and [Media Server](https://github.com/RestComm/RestComm-Core/files/112945/lcm-issue-media-server.txt) logs to help trace the call flow.

![lcm-issue](https://cloud.githubusercontent.com/assets/7796608/12730036/af7a2c28-c921-11e5-8c8d-6c1bd5a80c96.png)

The connections in red represent resources that were NOT deleted.
The connections in blue represented resources that were created without necessity.

It's important to notice that an endpoint with at least one or more connections will never be deleted on the Media Server side. This way, only the endpoints **ivr/1** and **ivr/2** are properly deleted.
The remaining endpoints are kept in memory, consuming memory and CPU! **This can rapidly lead to a high CPU consumption!**

Some notes worth mentioning to summarize the problem:
1. Seems like VoiceInterpreter has failed to initialize Bridge cleanup process before moving to Conference setup.
2. Conference workflow seems to create 2 extra (unecessary) connections, 4f and 5f, when Phone B re-joins the Conference as a moderator. The old connections, 4d and 5e, are not destroyed.
3. The conference is not destroyed because it assumes a participant is still in it. This problem happens when Phone B re-joins as moderator. Once this problem is fixed, then the conference room and its IVR endpoint shall be destroyed automatically.

Regards

**Comment by gvagenas** [comment]
@hrosa prepared a patch that properly cleans up MMS endpoints and connections.
Please check attached pcap file and confirm it fine.
From the MMS console I can see all connection and endpoints are released.
[trace_for_issue836.pcap.zip](https://github.com/RestComm/RestComm-Core/files/117834/trace_for_issue836.pcap.zip)

**Comment by hrosa** [comment]
@gvagenas I confirm cleanup is working perfectly. Great job.

**Comment by deruelle** [comment]
great job @hrosa and @gvagenas. That means we can proceed to ask the customer to test the MMS and RestComm CPU improvements soon ?

**Comment by hrosa** [comment]
@deruelle As soon as we merge this patch with https://github.com/RestComm/RestComm-Core/pull/840
