### ISSUE TITLE
Minimum Requirements to run RestComm?

### ISSUE THREAD

**Issue by arslan70** [RestComm/RestComm-Core#857]
I'm trying to run restcomm via docker on a core i5 @ 2.30GHz machine with 4GB RAM. OS is ubuntu 14 server edition, so there is no overhead of GUI. 

When the container is started the memory is fully utilized, the cpu load goes insane and the container doesn't respond in an orderly fashion. 

I know the details I'm providing are very vague but I couldn't find what are the minimum requirements in any documentation and can't figure out why memory and cpu are overloaded.

**Comment by deruelle** [comment]
Can you please post your questions on http://stackoverflow.com/questions/tagged/restcomm ?
