### ISSUE TITLE
Conference is not being released at the end of SIPp run using conference applicaiton

### ISSUE THREAD

**Issue by RomanDS** [RestComm/RestComm-Core#894]
Hi @hrosa,
this is the issue where I ran 30cps in a single run and got no errors in the logs but the conference was not released at the end of the test. Is that the expected behavior?
[P.zip](https://github.com/RestComm/RestComm-Core/files/143200/P.zip)

**Comment by hrosa** [comment]
@RomanDS RestComm should destroy the conference room when number of participants reaches zero.

**Comment by hrosa** [comment]
Going through the logs, I see that Conference believes it still has 6 participants in it:

> 13:11:01,222 INFO  [org.mobicents.servlet.restcomm.telephony.Conference - 72] (RestComm-akka.actor.default-dispatcher-49) ################################## CONFERENCE CALLS: 6

That is why the conference room is not destroyed.

**Comment by RomanDS** [comment]
Yeah, that is what I would expect. Could this be some code issue in a case where there is a limit of conferees allowed and it gets exceeded the count of who is in a conference gets messed up?



Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by hrosa** [comment]
@RomanDS I don't think so, the VoiceInterpreter first checks the current number of participants in the conference room before joining the new participant.

As you can see [here](https://github.com/RestComm/RestComm-Core/blob/master/restcomm/restcomm.interpreter/src/main/java/org/mobicents/servlet/restcomm/interpreter/VoiceInterpreter.java#L2030), If conference room is already full, then join process is aborted and RestComm keeps processing any RCML tag following the Dial (if any).

**Comment by RomanDS** [comment]
Ok, so the logs that I sent you indicate that there are still 6 parties in a conference but there is no one present from SIPp side of things. Even XMS Media Server shows only one connection (aka, conference control leg).

**Comment by hrosa** [comment]
@RomanDS I've spent some time looking into this. That log trace can be misleading under concurrency scenario.

I will try to provide a patch with more accurate logs tomorrow to help us nail this one.

**Comment by hrosa** [comment]
@RomanDS Try this patch please [restcomm.telephony-7.6.0-SNAPSHOT.jar.zip](https://github.com/RestComm/RestComm-Core/files/146504/restcomm.telephony-7.6.0-SNAPSHOT.jar.zip)

**Comment by RomanDS** [comment]
This is ok to run on top of version 30 + overlays given before, correct?



Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by RomanDS** [comment]
Hi @hrosa, I just ran the 60 cps scenario 4 times and it seems that the conference is now being cleaned up.

**Comment by hrosa** [comment]
Great @RomanDS !

**Comment by hrosa** [comment]
New Conference state diagram depicting new cleanup process:

![conference](https://cloud.githubusercontent.com/assets/7796608/13329958/a1497f7a-dbee-11e5-8aa3-db59d21569ef.png)
